import Link from "next/link";
import { Plus, Users } from "lucide-react";
import { getClients } from "@/lib/db/crm";

export const metadata = { title: "Expedientes" };

const labels: Record<string, string> = { NEW: "Nuevo", WAITING_DOCUMENTS: "Esperando documentos", UNDER_REVIEW: "En revisión", DOCUMENTS_COMPLETE: "Documentación completa", STARTED: "Iniciado", IN_PROGRESS: "En proceso", READY_FOR_DELIVERY: "Listo para entrega", COMPLETED: "Finalizado", ON_HOLD: "En pausa", REJECTED: "Rechazado", CANCELLED: "Cancelado" };
const active = new Set(["NEW", "WAITING_DOCUMENTS", "UNDER_REVIEW", "DOCUMENTS_COMPLETE", "STARTED", "IN_PROGRESS", "READY_FOR_DELIVERY", "ON_HOLD"]);

export default async function ExpedientsPage(props: { searchParams: Promise<{ status?: string | string[]; filter?: string | string[] }> }) {
  const [clients, params] = await Promise.all([getClients(), props.searchParams]);
  const status = typeof params.status === "string" ? params.status : undefined;
  const filter = typeof params.filter === "string" ? params.filter : undefined;
  const shown = clients.filter((client) => status ? client.procedures.some((procedure) => procedure.status === status) : filter === "active" ? client.procedures.some((procedure) => active.has(procedure.status)) : true);
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Administración</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-navy">Expedientes</h1><p className="mt-2 text-sm text-slate-600">Un solo lugar para gestionar clientes, trámites, documentos, vehículos y finanzas.</p></div><Link className="button" href="/admin/clientes/nuevo"><Plus size={17} />Nuevo cliente</Link></div><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{shown.length ? <div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Expediente</th><th className="px-5 py-4">Contacto</th><th className="px-5 py-4">Tipo</th><th className="px-5 py-4">Vehículos</th><th className="px-5 py-4">Trámites activos</th><th className="px-5 py-4">Documentos</th><th className="px-5 py-4">Estado reciente</th></tr></thead><tbody className="divide-y divide-slate-100">{shown.map((client) => { const name = client.company?.legalName ?? (`${client.firstName ?? ""} ${client.lastName ?? ""}`.trim() || "Perfil incompleto"); const recent = client.procedures[0]; const pending = client.documents.filter((document) => ["PENDING", "RECEIVED", "UNDER_REVIEW"].includes(document.status)).length; return <tr className="hover:bg-slate-50" key={client.id}><td className="px-5 py-4"><Link href={`/admin/expedientes/${client.id}`} className="font-semibold text-blue hover:text-navy">{name}</Link><p className="mt-1 text-xs text-slate-400">CLI-{client.id.slice(-6).toUpperCase()} {client.userId ? "· Registro web" : "· Alta administrativa"}</p></td><td className="px-5 py-4 text-slate-600">{client.phone ?? "-"}<p className="text-xs">{client.email ?? ""}</p></td><td className="px-5 py-4 text-slate-600">{client.type === "COMPANY" ? "Empresa" : "Persona física"}</td><td className="px-5 py-4 text-slate-600">{client._count.vehicles}</td><td className="px-5 py-4 text-slate-600">{client.procedures.filter((procedure) => active.has(procedure.status)).length}</td><td className="px-5 py-4 text-slate-600">{pending ? `${pending} por revisar` : "Al día"}</td><td className="px-5 py-4 text-slate-600">{recent ? labels[recent.status] : "Sin trámites"}</td></tr>; })}</tbody></table></div> : <div className="grid min-h-70 place-items-center p-8 text-center"><div><Users className="mx-auto text-slate-300" size={34} /><p className="mt-4 font-semibold text-navy">No hay expedientes para este filtro</p><Link className="button mt-5" href="/admin/expedientes">Limpiar filtros</Link></div></div>}</section></div>;
}
